num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))
diferenca_absoluta = abs(num1 - num2)
resultado_final = round(diferenca_absoluta, 2)
print(f"A diferença absoluta entre os números é: {resultado_final}")